server:
  port: 8080
spring:
  application:
    name: reservation-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///reservation_system?serverTimezone=Asia/Shanghai
    username: root
    password: 010519
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 010519
  mvc:
    servlet:
      load-on-startup: 1
sa-token:
  token-name: reservation
  is-concurrent: true
  is-share: false
  is-write-header: false
  timeout: 604800
  max-login-count: 2
  is-print: false
  is-log: true
  active-timeout: 259200
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
alipay:
  app-id: 9021000136632585
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjEBWdQnf2k5y6A6KHaXVRI/6pBwb+MOtnSkRxzHN5MElBX/IHcw0PUMbSYHhw3yYmCGmmg7PCd+rGCxO+UsFxs0CtSu90rEHCAMaNATUoiJ6cps+S+cPb4tp/JKwGKYwnW50xcumdQspW3aX0HllKp477zGLPsi8siizUapzFBzkoZDhpCsDdqMT0YYLzTs0fIwrOfXjKMN7vk7tO5OXN9AE7DGBAs0QrqN/i6z5B/vxuzSz45pjT+28F47V4ekZMBicnwSvYMEpxrPn2TQo0KdkvYJaPXn/bT/J3iyZsA+yaCAXC4Bl/GmCMC9WqhA4rH/oKz15ilbqk215XzDkLwIDAQAB
  app-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMQFZ1Cd/aTnLoDoodpdVEj/qkHBv4w62dKRHHMc3kwSUFf8gdzDQ9QxtJgeHDfJiYIaaaDs8J36sYLE75SwXGzQK1K73SsQcIAxo0BNSiInpymz5L5w9vi2n8krAYpjCdbnTFy6Z1CylbdpfQeWUqnjvvMYs+yLyyKLNRqnMUHOShkOGkKwN2oxPRhgvNOzR8jCs59eMow3u+Tu07k5c30ATsMYECzRCuo3+LrPkH+/G7NLPjmmNP7bwXjtXh6RkwGJyfBK9gwSnGs+fZNCjQp2S9glo9ef9tP8neLJmwD7JoIBcLgGX8aYIwL1aqEDisf+grPXmKVuqTbXlfMOQvAgMBAAECggEADaa5g5zZcBtQreu0X9xjXNAS2mRuCJGrVW/I7jWXz9tI6jcc2GGm+AuPHWGKAwgepjgoSjiEyHY/5hNyAGvf/RC5Yb8HM/nNMGd05nlN5RYsCvm3X5X296l/QHlasJuEgd5deV8wLZZPiTqK3lzijvpl5QtSfWL2kvTJN3q6xss/rJYB/3vi1am9ECbfqZ7Hrl4j6uyMJkWvUpFzEPoClGRhV8BbChcFjg+V1ySfMify0dTVRWYDGJiiPUJoiaURly9WxJ2aidCTQ+V2XptDiAxvZ/D1WAQjDnIHj4Pjuk+5P43S8PPcp4c8Ge5L/D8ZpLxGMWt0BwAUS/qF3dPE0QKBgQDi8Saq44MIvju+T4tFAdMN7eJ0tIQ761ryo254jcFZEItnnswLZgyti7oUlmnvLMnUCsdevbzA7ijhRZeLXZnGQwRsPYiM1e7u4eOF/tIMSOjQJ8sQgr3QlfYljN3tm3WSjZw0MS4NdE/YHTGxrzCTaFkz64YBKJkPWxOOaMB+qQKBgQCeNZWnLoqXF2mXpi5QJT5xE2z7dwSc0BimT4noClyid2mgYx6iqY0StYwdmFamN9qhP+lqaI2hy6/z6CH/1GNroxQw3TxwlOPDrwxol6iykfByIwFHhfFQfPKi2dt8COfWR/ONgG9BpBOURqoX+b8aas0iD7u/E1w0Oti9erpLFwKBgCmpOX7/myt8uLz8H0YAyrzw4bSo+umBEEYgyIPrCgaOqfjQxwaEqmklkHh9EF9u6nI5tFXpIQCN+AU64FIeUb96yBISzcGE+IL0Bu+vUuIcdFjaJUYXqj7jeLd1/7vB4TiRNI7ERH8Fzi6PVXMYBSPacR296/DEgiy2fIWVJ1lZAoGBAJwT5PWvlo4ETOmMyjfK5lULgwJ5ohVJvmekJDrEriqhf5T49Coo9sG0VOyFc0Y75/YYZR/S0ZcCqS0InzIRx5tSoQKr34p5eFF+idFNfOHd08Xl/scevrhW68/4+OzepEjjZsT8JcYuJhqrs/Y/LmbTYlfuCZwxb08flt8nCk41AoGBAIkrulM/MSCkwup3xj8aOU5nrf7x1iKKHkWdOktoL2jaVY6TnxzryLjk6H5xxoxU2OIe9Af5C0Fke2O3wNz4T4ORqAuShwr/ivvnImZApgdAfCLDkWRFAzqgrW6fvIzbGEHcCFx/wuTcqmNuLxNa0YicZZeSugzJ0gG/AmHWQAkx
redisson:
  server-mode: single
  address: redis://127.0.0.1:6379
  password: 010519
  database: 0
order:
  lock:
    lock-type: distributed
dromara:
  x-file-storage:
    default-platform: qiniu-kodo-1
    thumbnail-suffix: ".jpg"
    qiniu-kodo:
      - platform: qiniu-kodo-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: irQN7435V6SMIB-MqH24DJEFhwj-vwPsD74z05gh
        secret-key: U4lzab5eLy34ZB5K3U-40SLtS3Eo7pU4c2axMG6N
        bucket-name: wongbuer-reservation-system
        domain: http://sb92bqshe.hn-bkt.clouddn.com/
        base-path: detailed_pic/ # 基础路径
logging:
  level:
    com.wong.reservation: trace