server:
  port: 8080
spring:
  application:
    name: reservation-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///reservation_system?serverTimezone=Asia/Shanghai
    username: root
    password: 010519
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 010519
  mvc:
    servlet:
      load-on-startup: 1
sa-token:
  token-name: reservation
  is-concurrent: true
  is-share: false
  is-write-header: false
  timeout: 604800
  max-login-count: 2
  is-print: false
  is-log: true
  active-timeout: 259200
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl