server:
  port: 8080
spring:
  application:
    name: reservation-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(cytV8TXEQvN6+JUttKabc8CQkx5bhKPH64vcjRY9MI4vafeIvMeCoH1KmPAz0VpTvvjb1r2BKXZzMOip2bvwvbarfXzc9oah2BQqJxV0Vd8nSQiy0WXFwUT67OBzG27d)
    username: ENC(O/2U0HPop+tnY6H+ltkOx7E73SLKMpDAfNmYh8Owl38s7WR8mTpg5ywqPoJoA0Tl)
    password: ENC(fl7rDnf/yWOSQ9anSV83jG8aE69k4Rrkfcz8Uv1VhK1DRpKfnqVfLKnzRqeJGZQC)
  data:
    redis:
      host: ENC(n+RQ2DicJf3WzUxF0AKEL2fNCGFO/9yZNpmLqr2Uy+Xe94NpM9gWAHCTjTAvP80L)
      port: 6379
      password: ENC(t6kp608ATGfOO+CIeizq+u8y5ztCZAQFnmnVJpO4ynSGxoIzYDrbUZoO19Ggr0lC)
      database: 0
  mvc:
    servlet:
      load-on-startup: 1
sa-token:
  token-name: reservation
  is-concurrent: true
  is-share: false
  is-write-header: false
  timeout: 604800
  max-login-count: 2
  is-print: false
  is-log: true
  active-timeout: 259200
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
alipay:
  app-id: ENC(NRUBoRnVAERrKjErPl0QoWJmpVYGpZeQJe8PVgAyNrKVpj3s/Hut0Luu29dDSgSSl4A7dyy3+uzIv1XKOyB3Pw==)
  alipay-public-key: ENC(Ksl7USepTP8oUiI5uXpkhubj0lNa37ibEh3szbQMS1JfvFdUyt9rOvhtBW6wAxkwDR1RT967yukgooq5u9ZH2i+u12TmmEGjtdx2kA9yhhL3AUFJq7A51u9K8m7iDu3dLwqesmQe1+kkre8FmDC4Su7nOCeLf1g00KGKhCqfCK3i61nbiw5/x1G9AssRPOQP+OpQsCjo//MJ3hpzOxp4saRlnc/MLQ4mQY6GW1FIJWdPVHrTvrR0s7LF2uN7nlRa3xB7B12pZr6KhfQKk33bTFjxkuAxAttmPbHWA3gSDyFB4VTN0R2jB3W2HLIbHusKuqOpw0h8X6s+Z8KbG03LsyW/aC0/EPCQjpyykA8nMT4tRMtOSbkcfCFWacdaK6i2q19LTEyyOhDP1QYLegGVpha+ReJPrjCVpwsrNwzEC972OfbVwmuAru00joJrCQjqka2LcAMRcc52F+8rSzJcvLGXr6V+muI3yPV717/xgQ2ASJ6JLfFESDyTFEEe4mWCh9scv0MQabKRacvmqScXa+VxHXqcz5DpA7TVvIkloOVNJHxq9vKcm6Y9CMW/VvMe)
  app-private-key: ENC(R+e/ItQXbDMu6DMC+Yve0kMds0JhhBkQLgXYzgupfKXoCSIx12Wi8n0tKTNMIUw0n5VaecgHZpRwfzIGFZmfa0ALHg5kPGGPtWAF7tp5dZutFRP1IIigptTrK4T7ntCucb9pSwSiXluc+XmKGw/i2W5NrMFpSswy5IZzdsoai/FFzfTYZ4HO0/O5qgJN7zkUkcWJQTi7qRJvmCbiawis33TcK22KKbsJNjGco2cWfJ6dRz6x6BUXHMMc9sNBIxJC3qcqgTOdG73n9E4vx6Yj+xLnTNfZ1PeMBWZd/ywqdw+JdlECr7cEIYs4B5kOrV14bRCoHZPf/9XAcezqvFZYB5gMVaygIWLSzUzaxk/GWCDOLfLhE21oi3nVBBfcVUX7rQL02Ph9VxoOEtpvFL9Tc1uOEF6HTK3gzylTV3CyBVfcPU+Lp7pymqiUdCPulV+5gXxd7j2gxE2BZwdnswwnPRJNANiTfv43kqF7aPys5hoLpZSbDI/g7hUwoVp2XKh6Ku1przRGvP9GdpUu6A/ysHTKyU8aBhIFaEgQbP+oh+AZv3Q/eCQnCi4eHlIZewbEXcGy91LK3bnwJ9bH26Zx81q6zcJpHMSZpHFbHRLrpze+Oi3auLWCdtPLxyk78LIs9RRDWoh3LkXfL8OxcKoZd6sfhUMCTH/yPp5RcjMZ6Bt3ZzljsAwDGu0//sVDQkdU/4eFhHEVYoVNxKTV48uSVJ7MS7pjqSfvh+OwYeu6/X3R9tGaRdnvm4FRZKyxRYEdkBWb/D2RjS6LuYu/e8rWcytgAw9IZ07PL6ZNPaUTziQ+9M2LfWCJpajR0w3nLnJfplt3IHoywpXQ43/pOYXldPgWDV5kfEfBbdFnWQmjpuLhHNnrujXT2UxuydXBFleMb1OHJGCRHaIjVRnQRUohfzv/zdNX6Dcjatsb5C9B32uh20bSl80eCZ2W5D1lZM/KdBcl54IBB4qsZeAS8CZTXP3BPvyW8oB86nv5vWuRmbOcGYbb2hO3PGEeC5Lag/gvYsfw0TY1Gsgig+IfjXsLZh47wz9d6LSsO4PjxTGJRutV1wRlFVljKZThNMINulX4EWq1MTe6p/T3fmPgDWw5J0WEmRExX3gqtJVvRJXbL9iukNXL/1Acia9AeMgrkFPm7VDMfTcbOPPFuJcfID3mIXLoravb9qNiHTjZzcZ+eNc2JGxNP7QKNy/571pmLd7vRkMgyW1oCS0AG+nD6TwWfQ87E9I689551q6C3NLiR97uk5TE64u30v/UMlYep4hKwsHbj5B55x2rE2Yyhi3e1yRWFqetlQ0gEnCXV+t0GFU6XTwBwSJYBr43VUX4rdfQst8K09Io4j7jtS06kVuBQjwfyn1x05zvQ2MsbJAcQJXOMOr8ZD8d69jTFHp9InSVBCMXfIGZXrVPnmeAgNFCL9sDsym1KTerNJtKTq/Bk/nj/9cVSnjVp4kzaGheOx3SmXWB9446/B/9EQte5R1r7YBCMFH9/hYgcmB5dps19I2Ry3OQPw9N4ZvAHD3tmHew67v0Em6Y8Z++btwHZZviLscxWM3sVJu54Lq15Z1yc6z+xfF4W66IA1098RuPlx++PmjIGX5DQ3H7iKi0qgQpIZgoDtS5Kc5q7v/ggrQP272XycbqLNKQkuH0Ytg009gcjvy+vot2KmOKdI1wO6P2OXi63q1YW0zy+uVJBL3ZBb9txLK0EH8GgZTP6UO0oM+gwLgd6fzuDxT2xaQfs5YeWB2SdyT3gGcJParY6FTPQ+fv05iEt/L+Pbr05fXX1IaSCQC7iwTNblYxS7u5vl2QbnovUAnB7CAVjBzGb7WKAATiC8Q1aoqtrsiDtR9CAShdrStjDptVp98JG33Zxyo5zbIHhvp/QtVwPlBjU9dROhVAZfapLg3KmcOD9YSShTybJP/+yz/Ru/TGAtMt3jF7O4N6hVdJ2POUwBChtpS3qSEof7GAwKPd6nnlfEZgFhALMi0VpinXYoCHAKY85ZmoG/G8gbpihftK5BUXFENr27yv/DG0mC5GhoN3H3UnodlyQwejXbSC4jLNdvoEXu6MeJLxBtEj6+J2bhBTuW2B0dtChWlAIqSKLB9Tr686aGzWWbNrOt6XbY06HxmPSQdY5bfXM8E54kwaYibznXw84g2XzFDBy//PXeIA6CS2dQVYgQEbKTkMfBJ3zhHK9mxp8KRwYExsYPCTMwPxYFeu/Nk=)
order:
  lock:
    lock-type: distributed
dromara:
  x-file-storage:
    default-platform: ENC(wDaGLm/pZi2khXG+MQ59e9wDixd5gaV65+e3igub8MP/eu8OyPAizP83uohXrOeP)
    thumbnail-suffix: ".jpg"
    qiniu-kodo:
      - platform: ENC(+3blY6sbwlnCkkMxfVl58Raf5pAGAGsrmn5xvdTlZXBjAuHZEEva3DgVo4UH0yoI) # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ENC(K7sjNH66C0aLO5LQzNyMmxY14wFbWLblsXUpI3eHRr4A4VImFmsRpsmk3t2Oel45kSoFKZyIXAQxXCbcgSi55ZfcYOBxWQ7RKXF9EwuzhOU=)
        secret-key: ENC(ErFkt5lpqzAlGE62QSLCHgEvFSEYS5bM3XOC9ki9qtlIiylng4TiXRUCmDu4y8qcMJVQT4SxyAW7MvICXqfoqoWbQsk/nNi83f+O45Wdbws=)
        bucket-name: ENC(rpLwjEH+AZJEKPJuZJDNADN47EG5Z9TUKJGcutH3OAzSE9M9IdzuKNyRSZ60cMjRh7SjuYjFAw7CUKXy9tU8aQ==)
        domain: ENC(U27fuh8JxJxxj5TziKzOIo7LrI7aDYOqxng3qiSCTa6pBBiR5rp5/+FXOyDAwDj9d3fVj9dy8DuzeHlzzvVrEJceGloAWCa17+m+4kZKLUk=)
        base-path: ENC(yOTfJe1wgrOmkjxuIueExGTnoITms1T5C6mrAmI5PXCwid1AZ+ySr7qRLGWkBYdD) # 基础路径

logging:
  level:
    com.wong.reservation: trace